### ISSUE TITLE
Error in vim 7.4.963: E117: Unknown function: operator#user#define

### ISSUE THREAD

**Issue by minaguib** [haya14busa/vim-operator-flashy#1]
```
Error detected while processing /Users/mina/.vim/bundle/vim-operator-flashy/plugin/operator/flashy.vim:
line   17:
E117: Unknown function: operator#user#define
```

**Comment by luizribeiro** [comment]
You probably need to install the [`vim-operator-user` plugin](https://github.com/kana/vim-operator-user). Maybe this dependency should be listed on the repo's README?

**Comment by AdamWhittingham** [comment]
Well timed question- I just hit this too and adding `vim-operator-user` resolved it for me. Thank you :+1:

**Comment by haya14busa** [comment]
Thanks! I updated README :+1:
