### ISSUE TITLE
How to change the flash color?

### ISSUE THREAD

**Issue by Chinggis6** [haya14busa/vim-operator-flashy#10]
Is there an easy variable to set inside `vimrc` or pass during installation through [Vim-Plug](https://github.com/junegunn/vim-plug), to let the user change the color of the flash?

It'd be esp. useful for users who use [solarized](https://github.com/altercation/vim-colors-solarized) colorscheme, because it just flashes in plain black color which is a bit unpleasant.

Thanks in advance.

**Comment by haya14busa** [comment]
:h g:operator#flashy#group

Please use 'Flashy' highlight group.

e.g.

> hi Flashy guibg=red
