### ISSUE TITLE
E117: Unknown function: operator#user#define (Neovim) 

### ISSUE THREAD

**Issue by ev-agelos** [haya14busa/vim-operator-flashy#2]
I installed it yesterday and today that i opened Neovim before it opens and shows the file, shows these 3 lines:

```
Error detected while processing /../......nvim/plugged/vim-operator-flashy/plugin/operator/flashy.vim:
line   17:
E117: Unknown function: operator#user#define
Press ENTER or type command to continue
```

**Comment by haya14busa** [comment]
Please make sure to install https://github.com/kana/vim-operator-user. ref: #1

**Comment by ev-agelos** [comment]
I didnt even read your documentation, sry.

It doesnt seem to work on me though, maybe it conflicts with [vim search pulse plugin](https://github.com/inside/vim-search-pulse), I really dont know I am just guessing.

EDIT: theres aready a closed issue with the same problem duh! really sry :/
