### ISSUE TITLE
Unknown function getcurpos when using yy

### ISSUE THREAD

**Issue by KabbAmine** [haya14busa/vim-operator-flashy#3]
Hi, thanks for this nice plugin.

An error occurs when using `yy`:
![flashy-error](https://cloud.githubusercontent.com/assets/5658084/12064453/5ab7c2d8-afd4-11e5-9f4b-39ef8bd238cf.png)

Either the function `getcurpos()` exists on the last vim versions either its just a mistake, and should then be replaced by `getpos('.')`.

**Comment by haya14busa** [comment]
Thanks, I fixed it :+1:
