### ISSUE TITLE
Tab/multi-byte characters support

### ISSUE THREAD

**Issue by machakann** [haya14busa/vim-operator-flashy#8]
Tab character and multi-byte characters sometimes have a displayed width which is not matched with its byte length. It seems that the [vital-coaster](https://github.com/osyo-manga/vital-coaster) function returns a pattern based on a apparent position instead of a byte position, how about replacing getpos() to virtcol() function (and line() function)?

https://github.com/haya14busa/vim-operator-flashy/blob/master/autoload/operator/flashy.vim#L47

Let me say thank you for this plugin.

**Comment by haya14busa** [comment]
Sorry for the late response. Can you give me a example?

**Comment by machakann** [comment]
Hi, what I want to mention is that a highlighted area is often shift in a line including tab/multibyte charactors. Please take a look at the GIF, there is a line starting from a tab cahracter and following two words. When I press `yiw` on the second words, what I expect is  `bar` was highlighted but actually it is not.

![operator-flashy_ss](https://cloud.githubusercontent.com/assets/480049/15453183/68b66102-203e-11e6-9f1b-3a733557ca88.gif)

**Comment by KabbAmine** [comment]
Same thing here, the indented lines are most of the time badly highlighted.

![flashy](https://cloud.githubusercontent.com/assets/5658084/16480269/42b5991e-3eb6-11e6-8b43-a877cde2b431.gif)

**Comment by KabbAmine** [comment]
Any update here? The plugin is barely usable with this issue :cry:
